### ISSUE TITLE
Late game round always give 2183 gold (possibly only duos)

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#105] opened 2020-04-11 13:52 UTC
![image](https://user-images.githubusercontent.com/50186248/79045605-57788c00-7c4f-11ea-82f5-0765f7c261ec.png)
not sure if intended so ive marked as bug and balance, 2183 is consistent between 4 different games played.

**Comment by SanctusAnimus** [comment] 2020-04-11 13:54
Round gold reward after 65th is constant `nRoundBaseBonus * math.pow(1.031, 65)`

**Comment by Draze22** [comment] 2020-04-11 13:55
So a feature not a bug?

**Comment by SanctusAnimus** [comment] 2020-04-11 13:57
yeah, that's intentional

**Comment by SanctusAnimus** [comment] 2020-04-28 11:15
Closing since it's a feature

**Closed by SanctusAnimus** 2020-04-28 11:15 UTC
Labels: balance, bug
