### ISSUE TITLE
Player had been in 0 duels while another had been in 3 duels

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#342] opened 2020-07-19 04:43 UTC
![image](https://user-images.githubusercontent.com/63279022/87867187-fab70b00-c9cd-11ea-940d-115181bfa79f.png)
![image](https://user-images.githubusercontent.com/63279022/87867202-102c3500-c9ce-11ea-9811-d378d8a94115.png)

My understanding is that there should be a maximum of 2 duel participation difference between any 2 players.

**Comment by darklordabc** [comment] 2020-07-20 06:19
@fcalife comment?

**Comment by fcalife** [comment] 2020-07-20 13:09
There's no hard cap. 3 is very unlikely, but possible. I'd wager a good amount that that player had a duel in the next 1-2eounds.

**Comment by SanctusAnimus** [comment] 2020-07-24 16:48
Not a bug, but a rare occasion, closing for now

**Closed by SanctusAnimus** 2020-07-24 16:48 UTC
Labels: bug
