### ISSUE TITLE
Players having issues with not being able to pick innates and abilities without first reconnecting to the game

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#338] opened 2020-07-19 02:17 UTC
![image](https://user-images.githubusercontent.com/63279022/87865502-86726c80-c9b9-11ea-8df4-4ff360d2f6d9.png)
![image](https://user-images.githubusercontent.com/63279022/87865506-b0c42a00-c9b9-11ea-91b7-d170a9f035f2.png)
![image](https://user-images.githubusercontent.com/63279022/87865508-bc175580-c9b9-11ea-8d65-c25ba8445058.png)
https://pastebin.com/itvzFz3q
![image](https://user-images.githubusercontent.com/63279022/87865517-d8b38d80-c9b9-11ea-8e5f-1ad2f91e124f.png)
https://pastebin.com/AJTQnptg

**Comment by SanctusAnimus** [comment] 2020-07-19 04:30
Well it's not that ability selection not working, they are telling that their hero was not displayed on the left. It probably caused by econ error we fixed but not uploaded, which caused hero precache to fail

**Comment by darklordabc** [comment] 2020-07-21 08:37
@SanctusAnimus did u fix this?

**Comment by SanctusAnimus** [comment] 2020-07-21 09:35
Should be fixed, I've waited for an update to confirm it

**Comment by SanctusAnimus** [comment] 2020-07-24 16:49
No more reports of it, closing

**Closed by SanctusAnimus** 2020-07-24 16:49 UTC
Labels: bug
